# Generated by Django 2.2.3 on 2019-09-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProduit', models.CharField(max_length=200)),
                ('familleProduit', models.CharField(max_length=200)),
                ('descriptionProduit', models.CharField(max_length=200)),
                ('prix', models.PositiveIntegerField()),
            ],
        ),
    ]
