# Generated by Django 2.2.5 on 2019-09-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Produit',
        ),
    ]
