# Generated by Django 2.2.5 on 2019-09-26 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
