# Generated by Django 2.2.5 on 2019-09-27 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_delete_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Vente',
        ),
    ]
