# Generated by Django 2.2.5 on 2019-09-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_auto_20190929_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalinfo',
            name='catalogue_is_down',
        ),
        migrations.RemoveField(
            model_name='globalinfo',
            name='crm_is_down',
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='catalogue_is_up',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='crm_is_up',
            field=models.BooleanField(default=True),
        ),
    ]
