# Generated by Django 2.2.5 on 2019-09-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0011_auto_20190929_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='date',
        ),
        migrations.AddField(
            model_name='customer',
            name='idClient',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='produit',
            name='packaging',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='quantiteMin',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
