# Generated by Django 2.2.5 on 2019-10-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0013_auto_20191008_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idClient', models.TextField(default='')),
                ('prenom', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('ptsFidelite', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('paiement', models.IntegerField(default=0)),
                ('compte', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
