# Generated by Django 2.2.5 on 2019-10-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0014_auto_20191012_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProduit', models.CharField(max_length=20)),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ventes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('prix', models.IntegerField()),
                ('client', models.CharField(max_length=20)),
                ('pointsFidelite', models.IntegerField()),
                ('modePaiement', models.CharField(max_length=10)),
                ('articles', models.ManyToManyField(to='djangoapp.ArticlesList')),
            ],
        ),
    ]
