# Generated by Django 2.2.5 on 2019-10-12 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0015_articleslist_ventes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleslist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='id',
        ),
        migrations.AlterField(
            model_name='articleslist',
            name='codeProduit',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produit',
            name='codeProduit',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('codeProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.Produit')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('codeProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.Produit')),
            ],
        ),
    ]
