# Generated by Django 2.2.5 on 2019-10-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0016_auto_20191012_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('prix', models.IntegerField()),
                ('client', models.CharField(max_length=20)),
                ('pointsFidelite', models.IntegerField()),
                ('articles', models.ManyToManyField(to='djangoapp.ArticlesList')),
            ],
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='caisse_is_up',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='tickets_last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Ventes',
        ),
    ]
