# Generated by Django 2.2.6 on 2019-10-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0017_auto_20191012_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('prix', models.IntegerField()),
                ('client', models.CharField(max_length=20)),
                ('pointsFidelite', models.IntegerField()),
                ('modePaiement', models.CharField(max_length=10)),
                ('articles', models.ManyToManyField(to='djangoapp.ArticlesList')),
            ],
        ),
        migrations.RemoveField(
            model_name='globalinfo',
            name='caisse_is_up',
        ),
        migrations.RemoveField(
            model_name='globalinfo',
            name='tickets_last_update',
        ),
        migrations.DeleteModel(
            name='Vente',
        ),
    ]
