# Generated by Django 2.2.6 on 2019-10-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0018_auto_20191015_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalinfo',
            name='caisse_is_up',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='tickets_last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
