# Generated by Django 2.2.6 on 2019-10-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0019_auto_20191015_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticlesList',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='Ventes',
            new_name='Vente',
        ),
    ]
