# Generated by Django 2.2.6 on 2019-10-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0021_auto_20191016_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='ventes',
        ),
        migrations.AddField(
            model_name='vente',
            name='articles',
            field=models.ManyToManyField(to='djangoapp.Article'),
        ),
    ]
