# Generated by Django 2.2.6 on 2019-10-17 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0022_auto_20191016_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitVendu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiteVendu', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='inventaire',
            name='codeProduit',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='articles',
        ),
        migrations.AddField(
            model_name='produit',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Inventaire',
        ),
        migrations.AddField(
            model_name='produitvendu',
            name='codeProduit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.Produit'),
        ),
        migrations.AddField(
            model_name='produitvendu',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.Vente'),
        ),
        migrations.AddField(
            model_name='vente',
            name='produits',
            field=models.ManyToManyField(through='djangoapp.ProduitVendu', to='djangoapp.Produit'),
        ),
    ]
