# Generated by Django 2.2.6 on 2019-10-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0023_auto_20191017_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitvendu',
            old_name='codeProduit',
            new_name='produit',
        ),
        migrations.RenameField(
            model_name='produitvendu',
            old_name='quantiteVendu',
            new_name='quantite',
        ),
    ]
