# Generated by Django 2.2.6 on 2019-10-19 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0024_auto_20191017_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVendu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vente',
            name='produits',
        ),
        migrations.AddField(
            model_name='produit',
            name='exclusivite',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.DeleteModel(
            name='ProduitVendu',
        ),
        migrations.AddField(
            model_name='articlevendu',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.Produit'),
        ),
        migrations.AddField(
            model_name='articlevendu',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.Vente'),
        ),
        migrations.AddField(
            model_name='vente',
            name='articles',
            field=models.ManyToManyField(through='djangoapp.ArticleVendu', to='djangoapp.Produit'),
        ),
    ]
