# Generated by Django 2.2.6 on 2019-10-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0025_auto_20191019_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlevendu',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoapp.Produit'),
        ),
        migrations.AlterField(
            model_name='articlevendu',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoapp.Vente'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='codeProduit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoapp.Produit'),
        ),
    ]
