# Generated by Django 2.2.6 on 2019-10-20 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0028_auto_20191019_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='codeProduit',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='quantite',
        ),
        migrations.AddField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='ArticleCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoapp.Produit')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoapp.Commande')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='articles',
            field=models.ManyToManyField(through='djangoapp.ArticleCommande', to='djangoapp.Produit'),
        ),
    ]
