# Generated by Django 2.2.6 on 2019-10-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0030_auto_20191020_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='date',
        ),
    ]
