# Generated by Django 2.2.6 on 2019-10-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0031_remove_commande_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='carteFid',
            field=models.IntegerField(default=-1),
        ),
    ]
