# Generated by Django 2.2.6 on 2019-10-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0032_client_cartefid'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
