# Generated by Django 2.2.6 on 2019-11-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0033_commande_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(default='En Cours', max_length=20),
        ),
    ]
