# Generated by Django 2.2.6 on 2019-11-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0034_commande_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='carteFid',
        ),
        migrations.RemoveField(
            model_name='client',
            name='paiement',
        ),
    ]
