# Generated by Django 2.2.6 on 2019-11-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0035_auto_20191106_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='client',
            field=models.CharField(max_length=50),
        ),
    ]
