# Generated by Django 3.0 on 2019-12-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0039_produit_prixapres'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='promo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prixApres',
            field=models.FloatField(default=0),
        ),
    ]
