# Generated by Django 3.0 on 2019-12-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0040_auto_20191216_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('idClient', models.TextField(default='')),
                ('codeProduit', models.CharField(max_length=200)),
                ('quantite', models.IntegerField()),
                ('promo', models.IntegerField(default=0)),
            ],
        ),
    ]
