# Generated by Django 3.0.2 on 2020-02-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0041_customersproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlevendu',
            old_name='quantite',
            new_name='quantity',
        ),
    ]
